name: build_package_x86_22.04

on:
  push:
    branches: [ master, "2.0", "2.2.x-evo" ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *
              
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Repository
        run: |
          sudo apt install -y curl
          sudo curl -1sLf \
          'https://dl.cloudsmith.io/public/openhd/openhd-2-2-evo/setup.deb.sh' \
          | sudo -E bash
          sudo apt update
          sudo apt upgrade -y
          sudo apt remove libunwind-13-dev 
          sudo apt install -y libunwind-dev libgstreamer-plugins-base1.0-dev
          sudo apt -y install ruby-dev libfmt-dev mavsdk openhd-qt
          sudo gem install fpm
          sudo apt install openhd-qt  
          sudo rm -f /etc/ld.so.conf.d/qt.conf
          sudo touch /etc/ld.so.conf.d/qt.conf
          sudo sh -c 'echo "/opt/Qt5.15.7/lib/" >/etc/ld.so.conf.d/qt.conf'
          sudo ldconfig
          export PATH="$PATH:/opt/Qt5.15.7/bin/"
          sudo rm -f /usr/bin/qmake
          sudo ln -s /opt/Qt5.15.7/bin/qmake /usr/bin/qmake
          echo "QT successfully linked" 

      - name: Install QGC source dependencies
        run:  sudo apt-get install -y libsdl2-dev

      - name: Install Gstreamer
        run:  sudo apt-get install -y libgstreamer1.0-0:amd64 libgstreamer1.0-dev

      - name: Install post-link dependencies
        run:  sudo apt-get install -y binutils patchelf

      - name: Build
        run:  |
              ls -a
              mkdir build
              cd build
              qmake ../qgroundcontrol.pro
              make -j2
              make install
